// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {article} from '../models';

export function GetArticles():Promise<Array<article.Article>>;
