import { createClient } from "@libsql/client"
import { drizzle } from "drizzle-orm/libsql"
import { sql } from "drizzle-orm"
import * as schema from "../lib/db/schema"

// ---------------------------------------------------------------------------
// DB 接続
// ---------------------------------------------------------------------------
function createDb() {
    const url = process.env.TURSO_DATABASE_URL
    const authToken = process.env.TURSO_AUTH_TOKEN

    if (!url || url === "libsql://" || url.startsWith("file:")) {
        const client = createClient({ url: url?.startsWith("file:") ? url : "file:local.db" })
        return drizzle(client, { schema })
    }

    return drizzle(createClient({ url, authToken: authToken || undefined }), { schema })
}

// ---------------------------------------------------------------------------
// シードデータ
// ---------------------------------------------------------------------------
type BookSeed = {
    title: string
    author: string
    publisher: string | null
    publishedYear: number | null
    isbn: string | null
    officialUrl: string | null
    memo: string | null
    tags: string[]
}

const seedBooks: BookSeed[] = [
    {
        title: "エリックエヴァンスのドメイン駆動設計",
        author: "Eric Evans",
        publisher: "翔泳社",
        publishedYear: 2013,
        isbn: "9784798126708",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798126708",
        memo: null,
        tags: ["DDD", "設計", "本質"],
    },
    {
        title: "ソフトウェアアーキテクチャの基礎",
        author: "Mark Richards、Neal Ford",
        publisher: "オライリー・ジャパン",
        publishedYear: 2022,
        isbn: "978-4-87311-982-3",
        officialUrl: "https://www.oreilly.co.jp//books/9784873119823/",
        memo: null,
        tags: ["アーキテクチャ", "本質"],
    },
    {
        title: "スタッフエンジニア",
        author: "Will Larson",
        publisher: "日経BP",
        publishedYear: 2023,
        isbn: "9784296070558",
        officialUrl: "https://bookplus.nikkei.com/atcl/catalog/23/04/07/00760/",
        memo: null,
        tags: ["キャリア"],
    },
    {
        title: "ドメイン駆動設計をはじめよう",
        author: "Vlad Khononov",
        publisher: "オライリー・ジャパン",
        publishedYear: 2024,
        isbn: "978-4-8144-0073-7",
        officialUrl: "https://www.oreilly.co.jp/books/9784814400737/",
        memo: null,
        tags: ["DDD", "設計", "本質"],
    },
    {
        title: "SREをはじめよう",
        author: "David N. Blank-Edelman",
        publisher: "オライリー・ジャパン",
        publishedYear: 2024,
        isbn: "978-4-8144-0090-4",
        officialUrl: "https://www.oreilly.co.jp/books/9784814400904/",
        memo: null,
        tags: ["SRE"],
    },
    {
        title: "現場で役立つシステム設計の原則",
        author: "増田亨",
        publisher: "技術評論社",
        publishedYear: 2017,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: ["アーキテクチャ"],
    },
    {
        title: "詳解Terraform",
        author: "Yevgeniy Brikman",
        publisher: "オライリー・ジャパン",
        publishedYear: 2020,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: ["SRE"],
    },
    {
        title: "入門監視",
        author: "Mike Julian",
        publisher: "オライリー・ジャパン",
        publishedYear: 2019,
        isbn: "978-4-87311-864-2",
        officialUrl: "https://www.oreilly.co.jp/books/9784873118642/",
        memo: null,
        tags: ["SRE", "本質"],
    },
    {
        title: "コンピュータビジョンのための実践機械学習",
        author: "Valliappa Lakshmanan、Martin Görner、Ryan Gillard",
        publisher: "オライリー・ジャパン",
        publishedYear: 2023,
        isbn: "978-4-8144-0038-6",
        officialUrl: "https://www.oreilly.co.jp/books/9784814400386/",
        memo: null,
        tags: ["AI", "CV"],
    },
    {
        title: "データ指向アプリケーションデザイン",
        author: "Martin Kleppmann",
        publisher: "オライリー・ジャパン",
        publishedYear: 2019,
        isbn: "978-4-87311-870-3",
        officialUrl: "https://www.oreilly.co.jp/books/9784873118703/",
        memo: null,
        tags: ["開発手法"],
    },
    {
        title: "コンピュータシステムの理論と実装",
        author: "Noam Nisan、Shimon Schocken",
        publisher: "オライリー・ジャパン",
        publishedYear: 2015,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "詳解 システム・パフォーマンス第2版",
        author: "Brendan Gregg",
        publisher: "オライリー・ジャパン",
        publishedYear: 2022,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "テスト駆動開発",
        author: "Kent Beck",
        publisher: "オーム社",
        publishedYear: 2017,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "融けるデザイン",
        author: "渡邊恵太",
        publisher: "ビー・エヌ・エヌ新社",
        publishedYear: 2015,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "データモデリングでドメインを駆動する",
        author: "杉本啓",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "コンテナセキュリティ",
        author: "Liz Rice",
        publisher: "インプレス",
        publishedYear: 2020,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "SIMPLICITY",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "SQLアンチパターン第2版",
        author: "Bill Karwin",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "データマネジメントが30分でわかる本",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "[入門]ドメイン駆動設計",
        author: "増田亨、田中ひさてる、奥澤俊樹、中村充志、成瀬允宣、大西政徳",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14317-6",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14317-6",
        memo: null,
        tags: ["DDD", "設計", "本質"],
    },
    {
        title: "マスタリングTCP/IP 入門編",
        author: "竹下隆史、村山公保、荒井透、苅田幸雄",
        publisher: "オーム社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "アジャイルサムライ",
        author: "Jonathan Rasmusson",
        publisher: "オーム社",
        publishedYear: 2011,
        isbn: "9784274068560",
        officialUrl: "https://www.ohmsha.co.jp/book/9784274068560/",
        memo: null,
        tags: ["アジャイル", "本質"],
    },
    {
        title: "入門モダンLINUX",
        author: "Brendan Burns",
        publisher: "オライリー・ジャパン",
        publishedYear: 2023,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "AIエージェント開発/運用入門",
        author: "",
        publisher: "SBクリエイティブ",
        publishedYear: null,
        isbn: null,
        officialUrl: "https://www.sbcr.jp/product/4815636609/",
        memo: null,
        tags: ["AI", "エージェント", "詳細"],
    },
    {
        title: "Webを支える技術",
        author: "山本陽平",
        publisher: "技術評論社",
        publishedYear: 2010,
        isbn: "978-4-7741-4204-3",
        officialUrl: "https://gihyo.jp/book/2010/978-4-7741-4204-3",
        memo: null,
        tags: ["ネットワーク", "詳細"],
    },
    {
        title: "Real World HTTP",
        author: "渋川よしき",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "技術リーダーシップのための14のヒント",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "EPUB3とは何か？",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ドメイン駆動設計実装モデリングガイド",
        author: "松岡幸一郎",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: "https://booth.pm/ja/items/1835632",
        memo: null,
        tags: ["DDD", "本質"],
    },
    {
        title: "大規模データ管理",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "A PHILOSOPHY OF SOFTWARE DESIGN",
        author: "John Ousterhout",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Go言語によるWebアプリケーション開発",
        author: "Mat Ryer",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "MLOps実装ガイド",
        author: "Yaron Haviv、Noah Gift",
        publisher: "オライリー・ジャパン",
        publishedYear: 2025,
        isbn: "978-4-8144-0120-8",
        officialUrl: "https://www.oreilly.co.jp/books/9784814401208/",
        memo: null,
        tags: ["AI", "MLOps"],
    },
    {
        title: "達人が教えるWebパフォーマンスチューニングISUCON",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Looks Good To Me",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Clean Architecture",
        author: "Robert C. Martin",
        publisher: "アスキードワンゴ",
        publishedYear: 2018,
        isbn: "978-4-04-893065-9",
        officialUrl: "https://asciidwango.jp/post/176293765750/clean-architecture",
        memo: null,
        tags: ["コーディング", "設計", "本質"],
    },
    {
        title: "モデルベース要件定義テクニック",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "俺たちと探求するLLMアプリケーションのオブザーバビリティ",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: "https://techbookfest.org/product/mn0L7GEm3s8Vhmxq971HEi",
        memo: null,
        tags: ["AI", "エージェント"],
    },
    {
        title: "リーダブルコード",
        author: "Dustin Boswell、Trevor Foucher",
        publisher: "オライリー・ジャパン",
        publishedYear: 2012,
        isbn: "978-4-87311-565-8",
        officialUrl: "https://www.oreilly.co.jp/books/9784873115658/",
        memo: null,
        tags: ["コーディング", "設計", "本質"],
    },
    {
        title: "良いコード/悪いコードで学ぶ設計入門",
        author: "仙塲大也",
        publisher: "技術評論社",
        publishedYear: 2022,
        isbn: "978-4-297-12783-1",
        officialUrl: "https://gihyo.jp/book/2022/978-4-297-12783-1",
        memo: null,
        tags: ["設計", "アーキテクチャ", "本質"],
    },
    {
        title: "コンピュータビジョン最前線Summer2025",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "RDRA2.0ハンドブック",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ゼロから作るDeep Learning",
        author: "斎藤康毅",
        publisher: "オライリー・ジャパン",
        publishedYear: 2016,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "改訂新版Go言語プログラミングエッセンス",
        author: "mattn",
        publisher: "技術評論社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ドメイン駆動設計サンプルコード＆FAQ",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "エンジニアのための時間管理術",
        author: "Thomas A. Limoncelli",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "なっとく！アルゴリズム第2版",
        author: "Aditya Y. Bhargava",
        publisher: "翔泳社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "エンジニアリングマネージャーのしごと",
        author: "James Stanier",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "プログラムはなぜ動くのか",
        author: "矢沢久雄",
        publisher: "日経BP",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Docker コンテナ開発・環境構築の基礎",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "初めてのGraphQL",
        author: "Eve Porcello、Alex Banks",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "クリエイター六法",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "初めてのGo言語",
        author: "Jon Bodner",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Binary Hacks Rebooted",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Pytorch 自然言語処理プログラミング",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "達人に学ぶDB設計徹底指南書",
        author: "ミック",
        publisher: "翔泳社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ドキュメント作成の基本",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "PythonによるAI・機械学習・深層学習アプリの作り方",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ハッカーの学校",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "The Rust Programming Language",
        author: "Steve Klabnik、Carol Nichols",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: "https://doc.rust-jp.rs/book-ja-pdf/book.pdf",
        memo: null,
        tags: ["言語", "Rust"],
    },
    {
        title: "ゾンビスクラムサバイバルガイド",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ハンズオンNode.js",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "AWSクラウドネイティブデザインパターン",
        author: "林政利、根本裕規、吉澤稔",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14337-4",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14337-4",
        memo: null,
        tags: ["SRE", "設計"],
    },
    {
        title: "SQL実践入門",
        author: "ミック",
        publisher: "技術評論社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "失敗から学ぶRDBの正しい歩き方",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "実践Next.js",
        author: "吉井健文",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14061-8",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14061-8",
        memo: null,
        tags: ["Next.js", "詳細"],
    },
    {
        title: "オブジェクト設計スタイルガイド",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ビジュアル情報処理",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "組織を変える五つの対話",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Pythonブートキャンプ",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "AWSの基本・仕組み・重要用語が全部わかる教科書",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "プログラミング言語の基礎概念",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "達人プログラマー",
        author: "David Thomas、Andrew Hunt",
        publisher: "オーム社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "GitHubCI/CD実践ガイド",
        author: "野村友規",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14173-8",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14173-8",
        memo: null,
        tags: ["DevOps"],
    },
    {
        title: "Tidy First?",
        author: "Kent Beck",
        publisher: "オライリー・ジャパン",
        publishedYear: 2024,
        isbn: "978-4-8144-0091-1",
        officialUrl: "https://www.oreilly.co.jp/books/9784814400911/",
        memo: null,
        tags: ["設計", "開発手法", "本質"],
    },
    {
        title: "効率的なGo",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "ソフトウェア開発現場の「失敗」集めてみた。",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "バックエンドエンジニアを目指す人のためのRust",
        author: "安東一慈、大西諒、徳永裕介、中村謙弘、山中雄大",
        publisher: "翔泳社",
        publishedYear: 2024,
        isbn: "9784798186016",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798186016",
        memo: null,
        tags: ["言語", "Rust"],
    },
    {
        title: "起業の科学",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "Go言語ハンズオン",
        author: "掌田津耶乃",
        publisher: "秀和システム",
        publishedYear: 2021,
        isbn: "9784798063997",
        officialUrl: "https://www.shuwasystem.co.jp/book/9784798063997.html",
        memo: null,
        tags: ["言語", "Go", "ハンズオン"],
    },
    {
        title: "HTML&CSSとWebデザイン 入門講座",
        author: "",
        publisher: null,
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "SREサイトリライアビリティエンジニアリング",
        author: "Betsy Beyer、Chris Jones、Jennifer Petoff、Niall Richard Murphy",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "プロを目指す人のためのTypeScript入門",
        author: "鹿野壮",
        publisher: "技術評論社",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "マイクロサービスアーキテクチャ",
        author: "Sam Newman",
        publisher: "オライリー・ジャパン",
        publishedYear: null,
        isbn: null,
        officialUrl: null,
        memo: null,
        tags: [],
    },
    {
        title: "現場で使える！機械学習システム構築実践ガイド",
        author: "澁井雄介",
        publisher: "翔泳社",
        publishedYear: 2022,
        isbn: "9784798179049",
        officialUrl: "https://www.seshop.com/product/detail/25429",
        memo: null,
        tags: ["AI", "機械学習"],
    },
    {
        title: "AIエンジニアのための機械学習システムデザインパターン",
        author: "澁井雄介",
        publisher: "翔泳社",
        publishedYear: 2021,
        isbn: "9784798169453",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798169453",
        memo: null,
        tags: ["AI", "機械学習"],
    },
    {
        title: "［作って学ぶ］ブラウザのしくみ",
        author: "土井麻未",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14546-0",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14546-0",
        memo: null,
        tags: ["ブラウザ", "ハンズオン"],
    },
    {
        title: "［作って学ぶ］OSのしくみⅠ",
        author: "hikalium",
        publisher: "技術評論社",
        publishedYear: 2025,
        isbn: "978-4-297-14859-1",
        officialUrl: "https://gihyo.jp/book/2025/978-4-297-14859-1",
        memo: null,
        tags: ["OS"],
    },
    {
        title: "Elixir実践入門",
        author: "栗林健太郎、大原常徳、大聖寺谷一樹、山内修、齋藤和也、隆藤唯章、高瀬英希",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14014-4",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14014-4",
        memo: null,
        tags: ["Elixir"],
    },
    {
        title: "Rustで学ぶWebAssembly",
        author: "清水智公",
        publisher: "技術評論社",
        publishedYear: 2024,
        isbn: "978-4-297-14413-5",
        officialUrl: "https://gihyo.jp/book/2024/978-4-297-14413-5",
        memo: null,
        tags: ["Rust", "WASM"],
    },
    {
        title: "Design It!",
        author: "Michael Keeling",
        publisher: "オライリー・ジャパン",
        publishedYear: 2019,
        isbn: "978-4-87311-895-6",
        officialUrl: "https://www.oreilly.co.jp//books/9784873118956/",
        memo: null,
        tags: ["アーキテクチャ"],
    },
    {
        title: "ソフトウェアエンジニアガイドブック",
        author: "Gergely Orosz",
        publisher: "オライリー・ジャパン",
        publishedYear: 2025,
        isbn: "978-4-8144-0121-5",
        officialUrl: "https://www.oreilly.co.jp/books/9784814401215/",
        memo: null,
        tags: ["キャリア"],
    },
    {
        title: "ソフトウェアアーキテクチャ・ハードパーツ",
        author: "Neal Ford、Mark Richards、Pramod Sadalage、Zhamak Dehghani",
        publisher: "オライリー・ジャパン",
        publishedYear: 2022,
        isbn: "978-4-8144-0006-5",
        officialUrl: "https://www.oreilly.co.jp//books/9784814400065/",
        memo: null,
        tags: ["アーキテクチャ"],
    },
    {
        title: "Effective TypeScript",
        author: "Dan Vanderkam",
        publisher: "オライリー・ジャパン",
        publishedYear: 2025,
        isbn: "978-4-8144-0109-3",
        officialUrl: "https://www.oreilly.co.jp/books/9784814401093/",
        memo: null,
        tags: ["言語", "TypeScript", "詳細"],
    },
    {
        title: "なぜ依存を注入するのか",
        author: "Steven van Deursen、Mark Seemann",
        publisher: "マイナビ出版",
        publishedYear: 2024,
        isbn: null,
        officialUrl: "https://book.mynavi.jp/ec/products/detail/id=143373",
        memo: null,
        tags: ["アーキテクチャ", "設計"],
    },
    {
        title: "ソフトウェア設計の結合バランス",
        author: "Vlad Khononov",
        publisher: "インプレス",
        publishedYear: 2025,
        isbn: "9784295022961",
        officialUrl: "https://book.impress.co.jp/books/1124101149",
        memo: null,
        tags: ["設計"],
    },
    {
        title: "ユーザーストーリーマッピング",
        author: "Jeff Patton",
        publisher: "オライリー・ジャパン",
        publishedYear: 2015,
        isbn: "978-4-87311-732-4",
        officialUrl: "https://www.oreilly.co.jp/books/9784873117324/",
        memo: null,
        tags: ["設計", "本質"],
    },
    {
        title: "エンジニアの知的生産術",
        author: "西尾泰和",
        publisher: "技術評論社",
        publishedYear: 2018,
        isbn: "978-4-7741-9876-7",
        officialUrl: "https://gihyo.jp/book/2018/978-4-7741-9876-7",
        memo: null,
        tags: ["キャリア", "読み物"],
    },
    {
        title: "安全なWebアプリケーションの作り方",
        author: "徳丸浩",
        publisher: "SBクリエイティブ",
        publishedYear: 2018,
        isbn: null,
        officialUrl: "https://www.sbcr.jp/product/4797393163/",
        memo: null,
        tags: ["セキュリティ"],
    },
    {
        title: "独習PHP",
        author: "山田祥寛",
        publisher: "翔泳社",
        publishedYear: 2021,
        isbn: "9784798168494",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798168494",
        memo: null,
        tags: ["PHP"],
    },
    {
        title: "PHPフレームワークLaravel入門",
        author: "掌田津耶乃",
        publisher: "秀和システム",
        publishedYear: 2025,
        isbn: "9784798075273",
        officialUrl: "https://www.shuwasystem.co.jp/book/9784798075273.html",
        memo: null,
        tags: ["PHP", "言語"],
    },
    {
        title: "フロントエンド開発のためのテスト入門",
        author: "吉井健文",
        publisher: "翔泳社",
        publishedYear: 2023,
        isbn: "9784798178639",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798178639",
        memo: null,
        tags: ["テスト"],
    },
    {
        title: "ドメイン駆動設計入門",
        author: "成瀬允宣",
        publisher: "翔泳社",
        publishedYear: 2020,
        isbn: "9784798150727",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798150727",
        memo: null,
        tags: ["DDD", "設計", "本質"],
    },
    {
        title: "SCRUM BOOT CAMP THE BOOK",
        author: "西村直人、永瀬美穂、吉羽龍太郎",
        publisher: "翔泳社",
        publishedYear: 2020,
        isbn: "9784798167282",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798167282",
        memo: null,
        tags: ["スクラム", "アジャイル"],
    },
    {
        title: "チームトポロジー",
        author: "Matthew Skelton、Manuel Pais",
        publisher: "日本能率協会マネジメントセンター",
        publishedYear: 2021,
        isbn: "9784820729631",
        officialUrl: "https://pub.jmam.co.jp/book/b593881.html",
        memo: null,
        tags: ["開発手法"],
    },
    {
        title: "WEB+DB PRESS VOL.133",
        author: "",
        publisher: "技術評論社",
        publishedYear: 2023,
        isbn: "978-4-297-13370-2",
        officialUrl: "https://gihyo.jp/magazine/wdpress/archive/2023/vol133",
        memo: null,
        tags: ["教養"],
    },
    {
        title: "プリンシプルオブプログラミング",
        author: "上田勲",
        publisher: "秀和システム",
        publishedYear: 2016,
        isbn: "9784798046143",
        officialUrl: "https://www.shuwasystem.co.jp/book/9784798046143.html",
        memo: null,
        tags: ["設計", "本質"],
    },
    {
        title: "フロントエンド開発のためのセキュリティ入門",
        author: "平野昌士",
        publisher: "翔泳社",
        publishedYear: 2023,
        isbn: "9784798170602",
        officialUrl: "https://www.seshop.com/product/detail/25546",
        memo: null,
        tags: ["セキュリティ"],
    },
    {
        title: "人工知能は人間を超えるか",
        author: "松尾豊",
        publisher: "KADOKAWA",
        publishedYear: 2015,
        isbn: "9784040800202",
        officialUrl: "https://www.u-tokyo.ac.jp/biblioplaza/ja/D_00055.html",
        memo: null,
        tags: ["AI", "読み物"],
    },
    {
        title: "ネットワークはなぜ繋がるのか",
        author: "戸根勤",
        publisher: "日経BP",
        publishedYear: 2007,
        isbn: "9784822283117",
        officialUrl: "https://bookplus.nikkei.com/atcl/catalog/07/P83110/",
        memo: null,
        tags: ["ネットワーク"],
    },
    {
        title: "日経テクノロジー展望2023世界を変える100の技術",
        author: "",
        publisher: "日経BP",
        publishedYear: 2022,
        isbn: null,
        officialUrl: "https://bookplus.nikkei.com/atcl/catalog/22/08/29/00341/",
        memo: null,
        tags: ["教養"],
    },
    {
        title: "アーキテクトの教科書",
        author: "米久保剛",
        publisher: "翔泳社",
        publishedYear: 2024,
        isbn: "9784798184777",
        officialUrl: "https://www.shoeisha.co.jp/book/detail/9784798184777",
        memo: null,
        tags: ["アーキテクチャ", "設計"],
    },
    {
        title: "未来IT図鑑 これからのAIビジネス",
        author: "谷田部卓",
        publisher: "エムディエヌコーポレーション",
        publishedYear: 2018,
        isbn: "978-4-8443-6823-6",
        officialUrl: "https://books.mdn.co.jp/books/3218203011/",
        memo: null,
        tags: ["AI", "読み物"],
    },
    {
        title: "はじめよう！要件定義",
        author: "羽生章洋",
        publisher: "技術評論社",
        publishedYear: 2015,
        isbn: "978-4-7741-7228-6",
        officialUrl: "https://gihyo.jp/book/2015/978-4-7741-7228-6",
        memo: null,
        tags: ["設計"],
    },
]

// ---------------------------------------------------------------------------
// 実行
// ---------------------------------------------------------------------------
async function seed() {
    const db = createDb()

    // 既存データをクリア（順序重要: 外部キー制約）
    await db.delete(schema.bookTags)
    await db.delete(schema.books)
    await db.delete(schema.tags)

    // 全タグを抽出・重複排除
    const allTagNames = [...new Set(seedBooks.flatMap((b) => b.tags))].filter(Boolean)

    // tags テーブルに挿入
    if (allTagNames.length > 0) {
        await db.insert(schema.tags).values(allTagNames.map((name) => ({ name })))
    }

    // name → id マップを作成
    const allTags = await db.select().from(schema.tags)
    const tagMap = new Map(allTags.map((t) => [t.name, t.id]))

    // books + bookTags を挿入
    let bookCount = 0
    let bookTagCount = 0

    for (const book of seedBooks) {
        const [inserted] = await db
            .insert(schema.books)
            .values({
                title: book.title,
                author: book.author,
                publisher: book.publisher,
                publishedYear: book.publishedYear,
                isbn: book.isbn,
                officialUrl: book.officialUrl,
                memo: book.memo,
                isRead: false,
            })
            .returning({ id: schema.books.id })

        bookCount++

        // bookTags を挿入
        const tagIds = book.tags.map((name) => tagMap.get(name)).filter((id): id is number => id !== undefined)
        if (tagIds.length > 0) {
            await db.insert(schema.bookTags).values(tagIds.map((tagId) => ({ bookId: inserted.id, tagId })))
            bookTagCount += tagIds.length
        }
    }

    console.log(`Seed completed:`)
    console.log(`  - ${allTagNames.length} tags`)
    console.log(`  - ${bookCount} books`)
    console.log(`  - ${bookTagCount} book-tag relations`)
}

seed().catch((err) => {
    console.error("Seed failed:", err)
    process.exit(1)
})
