// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"back/blog/domain"
	"time"
)

type Article struct {
	ID           int             `json:"id"`
	Title        string          `json:"title"`
	CategoryID   int             `json:"categoryId"`
	Category     domain.Category `json:"category"`
	Content      string          `json:"content"`
	FeaturePoint int             `json:"featurePoint"`
	IsPublished  bool            `json:"isPublished"`
	CreatedAt    time.Time       `json:"createdAt"`
	EditedAt     time.Time       `json:"EditedAt"`
}

type EditArticle struct {
	ID       int              `json:"id"`
	Title    *string          `json:"title,omitempty"`
	Content  *string          `json:"content,omitempty"`
	Category *domain.Category `json:"category,omitempty"`
}

type InsertDto struct {
	Title        string          `json:"title"`
	Category     domain.Category `json:"category"`
	Content      string          `json:"content"`
	FeaturePoint int             `json:"featurePoint"`
	IsPublished  bool            `json:"isPublished"`
}

type InsertFromNotionDto struct {
	PageID   string          `json:"pageId"`
	Category domain.Category `json:"category"`
}

type Mutation struct {
}

type Query struct {
}
