// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"back/blog/domain"
	"time"
)

type Article struct {
	ID           int        `json:"id"`
	PageID       string     `json:"pageId"`
	Title        string     `json:"title"`
	Contents     []*Content `json:"Contents"`
	FeaturePoint int        `json:"featurePoint"`
	IsPublished  bool       `json:"isPublished"`
	CreatedAt    time.Time  `json:"createdAt"`
	EditedAt     time.Time  `json:"EditedAt"`
}

type Content struct {
	ID           int    `json:"id"`
	ArticleID    int    `json:"articleId"`
	Order        int    `json:"order"`
	Type         string `json:"type"`
	Text         string `json:"text"`
	Bold         bool   `json:"bold"`
	Italic       bool   `json:"italic"`
	StrikThrough bool   `json:"strikThrough"`
	UnderLine    bool   `json:"underLine"`
	Code         bool   `json:"code"`
}

type EditArticle struct {
	ID       int              `json:"id"`
	Title    *string          `json:"title,omitempty"`
	Content  *string          `json:"content,omitempty"`
	Category *domain.Category `json:"category,omitempty"`
}

type InsertDto struct {
	PageID   *string          `json:"pageId,omitempty"`
	Category *domain.Category `json:"category,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
