// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Annotation struct {
	Bold         bool `json:"bold"`
	Italic       bool `json:"italic"`
	StrikThrough bool `json:"strikThrough"`
	UnderLine    bool `json:"underLine"`
	Code         bool `json:"code"`
}

type Article struct {
	ID       uint     `json:"id"`
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category Category `json:"category"`
}

type Content struct {
	Type        string      `json:"type"`
	Annotations *Annotation `json:"annotations"`
	Text        string      `json:"text"`
}

type EditArticle struct {
	ID       uint      `json:"id"`
	Title    *string   `json:"title,omitempty"`
	Content  *string   `json:"content,omitempty"`
	Category *Category `json:"category,omitempty"`
}

type Mutation struct {
}

type NewArticle struct {
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category Category `json:"category"`
}

type NotionArticle struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	CreatedAt time.Time  `json:"createdAt"`
	EditedAt  time.Time  `json:"EditedAt"`
	Contents  []*Content `json:"Contents"`
}

type Query struct {
}

type Category string

const (
	CategoryClimbing    Category = "CLIMBING"
	CategoryEngineering Category = "ENGINEERING"
	CategoryLife        Category = "LIFE"
)

var AllCategory = []Category{
	CategoryClimbing,
	CategoryEngineering,
	CategoryLife,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryClimbing, CategoryEngineering, CategoryLife:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
